version: "3.8"

services:
  db:
    image: postgres:14
    container_name: ${DB_CONTAINER_NAME:-nextjs-trpc-boilerplate-postgres}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nextjs-trpc-boilerplate
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
