import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import Navbar from "./_components/navbar/navbar-wrapper";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Next JS TRPC Boilerplate",
  description: "Generated by create-t3-app and customized by dodycode",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <NextTopLoader />
          <Navbar />
          <main className="mx-auto mt-36 max-w-6xl">{children}</main>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
